### ISSUE TITLE
Task list for first release of package

### ISSUE THREAD

**Issue by nickruggeri** [HGX-Team/hypergraphx#2]
# Open tasks
A list of open tasks, both more to less important ones, before the release of the package.

### Linalg
Tests to be added for `hoinetx.linalg`

- [ ] tests for `incidence_matrix`
- [ ] tests for `incidence_matrix_by_order`
- [ ] tests for `incidence_matrices_all_orders`
- [ ] tests for `laplacian_matrix_by_order`
- [ ] tests for `laplacian_matrix_all_orders`
- [ ] tests for `compute_multiorder_laplacian`
- [ ] tests for `are_commuting`

### Measures
Tests to be added for `hoinetx.measures`.

- [ ] there are some basic tests for `sub_hypergraph_centrality`. We still need to test the correctness of the final calculations. It would be ideal to construct some small hypergraphs, compute their analytical eigenvector and eigenvalues, and check that for these the function returns the correct sub-hypergraph centrality.

### Linalg

- [ ] For all the Laplacian-related functions in `hoinetx.linalg`: do we need to add the `return_mapping` similar to other functions in `linalg`? 
- [ ] Similar question for function for all function split by order (e.g. `incidence_matrix_by_order` etc.). What is the correct mapping?

## Documentation
Docstring and other stuff

- [ ] in the documentation of `Hypergraph` maybe add the following observation? Nodes can be anything, and are given inside the edge list. However, they need to respect two conditions (as far as I can tell from the code):
        - first, they need to be comparable inside a sorting operation inside every hyperedge (since hyperedges are sorted during the hypergraph creation)
        - second, they need to be hashable, since they are keys of the `Hypergraph._neighbours` dictionary.
  In practice, most immutable native Python types work, as well as any custom object that implements `__hash__` (for hasing) and `__ge__`, `__le__`, etc. (for comparisons)
- [x] #3
